/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false packages/jelly-party-server/src/worker-configuration.d.ts` (hash: abf205e443de84cee9a65d01f2782d6b)
interface __BaseEnv_Env {
	ANALYTICS_DB: D1Database;
	PARTY_CREATION_RATE_LIMITER: RateLimit;
	PARTY_CONNECTION_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	MAX_PARTIES_PER_MONTH: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	PARTY: DurableObjectNamespace<import("./main").Party>;
	PARTY_QUOTA: DurableObjectNamespace<import("./main").PartyQuota>;
	LIVE_STATS: DurableObjectNamespace<import("./main").LiveStats>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
		durableNamespaces: "Party" | "PartyQuota" | "LiveStats";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_PARTIES_PER_MONTH" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
